version: "3.8"

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./server:/server
      - /server/node_modules
    command: ["npm", "start"]

  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    volumes:
      - ./client:/client
      - /client/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]